#fraud-detection-service/dockerfile
# mvn clean package -DskipTests -> command to make jar file -> notification-service-0.0.1-SNAPSHOT.jar (ls target to view the file)

# docker image command -> docker build -t notification-service:latest .

# command to run docker file -> docker run -p 8085:8085 --network bank-fraud_banking-network notification-service:latest

# Step 1: Use Java 17 as the base image
FROM eclipse-temurin:17-jre

# Step 2: Set working directory inside the container
WORKDIR /app

# Step 3: Copy the built jar file
COPY target/notification-service-0.0.1-SNAPSHOT.jar app.jar

# Step 4: Expose port
Expose 8085

# Step 5: Run the jar
ENTRYPOINT ["java", "-jar", "app.jar"]