spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://host.docker.internal:3307/account_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8083
#Razorpay configuration
razorpay:
  key:
    id: REDACTED_RAZORPAY_KEY_ID
    secret: REDACTED_RAZORPAY_KEY_SECRET
  webhook-secret:
management:
  endpoints:
    web:
      exposure:
        include: health, info
