#account-service/dockerfile

# Step 1: Use Java 17 as the base image
FROM eclipse-temurin:17-jre

# Step 2: Set working directory inside the container
WORKDIR /app

# Step 3: Copy the built jar file
COPY target/account-service-0.0.1-SNAPSHOT.jar app.jar

# Step 4: Expose port
Expose 8081

# Step 5: Run the jar
ENTRYPOINT ["java", "-jar", "app.jar"]